version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    groups:
      develop:
        patterns:
          - "*"
    commit-message:
      prefix: build
      include: scope
    labels:
      - dependencies
    rebase-strategy: auto
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
    commit-message:
      prefix: ci
      include: scope
    labels:
      - dependencies
    rebase-strategy: auto
