version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - pip install ".[docs]"
    - |
      ft3 docs . \
        --index-from-readme \
        --include-private-modules \
        --author dan@1howardcapital.com \
        --version $(ft3 --version) \
        --site-map-url https://ft3.readthedocs.io/en/stable
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - cp -r docs/html/ $READTHEDOCS_OUTPUT
